swarm_bt_tasker:
  ros__parameters:
    use_sim_time: false
    global_frame: gps_origin
    robot_base_frame: base_link
    odom_topic: odometry
    enable_groot_monitoring: False
    groot_zmq_publisher_port: 1666
    groot_zmq_server_port: 1667
    default_bt: ""
    bt_loop_duration: 10
    default_server_timeout: 3000
    plugin_lib_names:
      - swarm_back_up_action_bt_node
      - swarm_spin_action_bt_node
      - swarm_wait_action_bt_node
      - swarm_is_stuck_condition_bt_node
      - swarm_goal_updated_condition_bt_node
      - swarm_distance_controller_bt_node
      - swarm_goal_updater_node_bt_node
      - swarm_recovery_node_bt_node
      - swarm_pipeline_sequence_bt_node
      - swarm_round_robin_node_bt_node
      - swarm_transform_available_condition_bt_node
      - swarm_time_expired_condition_bt_node
      - swarm_distance_traveled_condition_bt_node
      - swarm_single_trigger_bt_node
      - swarm_is_battery_low_condition_bt_node

      - swarm_set_transform_to_blackboard_action
      - swarm_goal_within_distance_decorator
      - swarm_extract_pose_fields_action
      - swarm_get_transformed_pose_action
      - swarm_while_running_control

      - swarm_controller_command_action
      - swarm_controller_state_condition
      - swarm_goal_reached_condition_bt_node
      - swarm_set_connect_to_swarm_action
      - swarm_fly_to_pose_action
      - swarm_set_pose_to_blackboard_action
      - swarm_morph_action
      - glp_approach_pose_action
      - glp_rotate_action
      - glp_translate_action


swarm_bt_tasker_rclcpp_node:
  ros__parameters:
    goal_reached_tol: 1.0
    use_sim_time: false
