glp_ros:
  ros__parameters:
    use_sim_time: false
    min_velocity: 0.01
    max_velocity: 2.0
    max_linear_acceleration: 1.2
    min_angular_approach_velocity: 0.03
    max_angular_approach_velocity: 0.25
    max_angular_acceleration: 0.3
    min_rotate_only_velocity: 0.1
    max_rotate_only_velocity: 0.3

    k1: 3.0
    k2: 2.0
    beta: 0.2
    lambda: 2.0
    via_point_distance: .85
    xy_goal_tolerance: 0.02 #0.05
    yaw_goal_tolerance: 0.05

    robot_radius: 0.26
    obstacle_lookahead_distance: 1.0
    idle_timeout: 10.0
    debug_trajectory: true
    enable_collision_checker: false
    control_loop_frequency: 25.0
    min_angular_velocity: 0.01
    heading_angular_acceleration: 0.2
    trajectory_generation_timeout: 1.5

    cmd_vel_topic: "command/setUgvSpeed"
    base_frame: "Drone1/fcu"
    global_frame: "Drone1/gps_origin"
    cycle_frequency: 10.0
    transform_tolerance: 1.0

glp_translate:
  ros__parameters:
    global_frame: Drone1/gps_origin
    cmd_vel_topic: "command/setUgvSpeed"
    base_frame: Drone1/fcu
    cycle_frequency: 10.0
    transform_tolerance: 1.0
    use_sim_time: false

glp_rotate:
  ros__parameters:
    global_frame: Drone1/gps_origin
    cmd_vel_topic: "command/setUgvSpeed"
    base_frame: Drone1/fcu
    cycle_frequency: 10.0
    transform_tolerance: 1.0

    use_sim_time: false
    max_rotational_vel: 3.0
    min_rotational_vel: 0.1
    rotational_acc_lim: 1.2

